spring:
  application.name: Users
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/postgres

